site_name: LeetCode Note
copyright: Copyright &copy; 2021-2022 MikuSugar
theme:
  language: zh
  name: material
  features:
    - navigation.tabs
  custom_dir: docs/templates
  favicon: imags/logo.png
  logo: imags/logo.png
repo_url: https://github.com/MikuSugar/LeetCode.git
repo_name: MikuSugar/LeetCode
site_description:  LeetCode Note

nav:
  - 主页: index.md
  - 周赛:
      - 第233场周赛: weekly/力扣第233场周赛.md
      - 第234场周赛: weekly/力扣第234场周赛.md
      - 第235场周赛: weekly/力扣第235场周赛.md
      - 第236场周赛: weekly/力扣第236场周赛.md
      - 第237场周赛: weekly/力扣第237场周赛.md
      - 第240场周赛: weekly/力扣第240场周赛.md
      - 第241场周赛: weekly/力扣第241场周赛.md
      - 第242场周赛: weekly/力扣第242场周赛.md
      - 第243场周赛: weekly/力扣第243场周赛.md
      - 第244场周赛: weekly/力扣第244场周赛.md
      - 第252场周赛: weekly/力扣第252场周赛.md
      - 第253场周赛: weekly/力扣第253场周赛.md
      - 第254场周赛: weekly/力扣第254场周赛.md
      - 第255场周赛: weekly/力扣第255场周赛.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta


